name: Lint

on:
  push:
    branches:
      - 'master'
      - 'develop'
      - 'feature/**'
  pull_request:
    branches:
      - 'master'
      - 'develop'
      - 'feature/**'

jobs:
  build:
    runs-on: ubuntu-24.04

    steps:
      - uses: actions/checkout@v4
      - run: echo "NODE_VERSION=$(cat .nvmrc)" >> $GITHUB_OUTPUT
        id: nvm
      - uses: actions/setup-node@v3
        with:
          cache: 'npm'
          node-version: ${{ steps.nvm.outputs.NODE_VERSION }}
      - run: npm install
      - run: npm run build:all
      - name: 'Slack notification'
        id: slack
        uses: slackapi/slack-github-action@v1.27.0
        with:
          channel-id: 'jsbuffer'
          payload-file-path: '.github/workflows/lint-finished-slack-message.json'
        env:
          SLACK_BOT_TOKEN: ${{ secrets.SLACK_BOT_TOKEN }}
