name: Test

on:
  push:
    branches:
      - 'master'
      - 'feature/**'
  pull_request:
    branches:
      - 'master'
      - 'develop'
      - 'feature/**'

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [16.x, 18.x, 19.x, 20.x]

    steps:
      - uses: actions/checkout@v4
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}
          cache: 'npm'
      - name: Install OS dependencies
        uses: awalsh128/cache-apt-pkgs-action@latest
        with:
          packages: cmake gcc g++
          version: 1.0
      - name: Install Node.js packages
        run: npm install
      - name: Build the project
        run: npm run build
      - name: Run tests
        run: npm run test
      - name: slack-send
        id: slack
        uses: slackapi/slack-github-action@v1.27.0
        with:
          channel-id: 'jsbuffer'
          message: 'Tests successfully concluded for commit: ${{github.sha}}.\n\nTriggered by ${{github.triggering_actor}}'
        env:
          SLACK_BOT_TOKEN: ${{ secrets.SLACK_BOT_TOKEN }}
