name: Test

on:
  push:
    branches:
      - 'master'
      - 'feature/**'
      - 'develop'
  # pull_request:
  #   branches:
  #     - 'master'
  #     - 'develop'
  #     - 'feature/**'

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [20.x]

    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          cache: 'npm'
      - name: Install OS dependencies
        run: |
          sudo apt install -y cmake gcc g++
      - name: Install Node.js packages
        run: npm install
      - name: Build the project
        run: npm run build
      - name: Run tests
        run: npm run test
      - name: Create Slack messages
        run: node scripts/notify.js --notification-type test-finished
        env:
          EVENT_PUSHER_NAME: '${{ github.event.pusher.name }}'
          EVENT_HEAD_COMMIT_ID: '${{ github.event.head_commit.id }}'
          EVENT_HEAD_COMMIT_MESSAGE: '${{ github.event.head_commit.message }}'
          EVENT_HEAD_COMMIT_TIMESTAMP: '${{ github.event.head_commit.timestamp }}'
          EVENT_HEAD_COMMIT_URL: '${{ github.event.head_commit.url }}'
          EVENT_REF: '${{ github.event.ref }}'
          EVENT_AFTER_COMMIT: '${{ github.event.after }}'
          EVENT_BEFORE_COMMIT: '${{ github.event.before }}'
          EVENT_COMPARE_URL: '${{ github.event.compare }}'
      - name: 'Slack notification'
        id: slack
        uses: slackapi/slack-github-action@v1.27.0
        with:
          channel-id: 'jsbuffer'
          payload-file-path: '.github/workflows/slack-messages/testFinishedSlackMessage.json'
        env:
          SLACK_BOT_TOKEN: ${{ secrets.SLACK_BOT_TOKEN }}
