name: Test

on:
  push:
    branches:
      - 'master'
      - 'feature/**'
  pull_request:
    branches:
      - 'master'
      - 'develop'
      - 'feature/**'

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [20.x]

    steps:
      - name: Print environment variables
        run: echo '${{ toJSON(github.event.head_commit.added) }}, ${{ toJSON(github.event.head_commit.modified) }}, ${{ toJSON(github.event.head_commit.removed) }}, ${{ github.event.head_commit.timestamp }}'
      - uses: actions/checkout@v4
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node-version }}
          cache: 'npm'
      - name: Install OS dependencies
        run: |
          sudo apt install -y cmake gcc g++
      - name: Install Node.js packages
        run: npm install
      - name: Build the project
        run: npm run build
      - name: Run tests
        run: npm run test
      - name: Create Slack messages
        run: node scripts/create-slack-messages.js
        env:
          COMMIT_ADDED_FILES: '${{ toJSON(github.event.head_commit.added) }}'
          COMMIT_MODIFIED_FILES: '${{ toJSON(github.event.head_commit.modified) }}'
          COMMIT_REMOVED_FILES: '${{ toJSON(github.event.head_commit.removed) }}'
          COMMIT_TIMESTAMP: '${{ toJSON(github.event.head_commit.timestamp) }}'
      - name: 'Slack notification'
        id: slack
        uses: slackapi/slack-github-action@v1.27.0
        with:
          channel-id: 'jsbuffer'
          payload-file-path: '.github/workflows/test-finished-slack-message.json'
        env:
          SLACK_BOT_TOKEN: ${{ secrets.SLACK_BOT_TOKEN }}
