name: Test

on:
  push:
    branches:
      - 'master'
      - 'feature/**'
      - 'develop'
  # pull_request:
  #   branches:
  #     - 'master'
  #     - 'develop'
  #     - 'feature/**'

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [20.x]

    steps:
      - uses: actions/checkout@v4
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node-version }}
          cache: 'npm'
      - name: Print environment variables
        run: |
          echo 'toJSON(github.event.push.commits) -> ${{ toJSON(github.event.push.commits) }}'
          echo 'toJSON(github.event.push) -> ${{ toJSON(github.event.push) }}'
          echo 'toJSON(github.event) -> ${{ toJSON(github.event) }}'
          echo '${{ toJSON(github.event) }}'
          echo '${{ toJSON(github) }}'
          echo 'github.event.push.commits -> ${{ github.event.push.commits }}'
          echo 'github.event.push.head_commit.modified -> ${{ github.event.push.head_commit.modified }}'
          echo 'toJSON(github.event.push.head_commit.modified) -> ${{ toJSON(github.event.push.head_commit.modified) }}'
          echo 'toJSON(github.event.push.commits.added) -> ${{ toJSON(github.event.push.commits.added) }}'
          echo 'toJSON(github.event.push.commits.modified) -> ${{ toJSON(github.event.push.commits.modified) }}'
          echo 'toJSON(github.event.push.commits.removed) -> ${{ toJSON(github.event.push.commits.removed) }}'
          echo 'github.event.push.commits.timestamp -> ${{ github.event.push.commits.timestamp }}'
          echo 'github.event.push.commits.added -> ${{ github.event.push.commits.added }}'
          echo 'github.event.push.commits.modified -> ${{ github.event.push.commits.modified }}'
          echo 'github.event.push.commits.removed -> ${{ github.event.push.commits.removed }}'
          echo 'github.event.push.commits.timestamp -> ${{ github.event.push.commits.timestamp }}'
      - name: Install OS dependencies
        run: |
          sudo apt install -y cmake gcc g++
      - name: Install Node.js packages
        run: npm install
      - name: Build the project
        run: npm run build
      - name: Run tests
        run: npm run test
      - name: Create Slack messages
        run: node scripts/create-slack-messages.js
        env:
          EVENT_PUSHER_NAME: '${{ github.event.pusher.name }}'
          EVENT_HEAD_COMMIT_ID: '${{ github.event.head_commit.id }}'
          EVENT_HEAD_COMMIT_MESSAGE: '${{ github.event.head_commit.message }}'
          EVENT_HEAD_COMMIT_TIMESTAMP: '${{ github.event.head_commit.timestamp }}'
          EVENT_HEAD_COMMIT_URL: '${{ github.event.head_commit.url }}'
          EVENT_REF: '${{ github.event.ref }}'
          EVENT_AFTER_COMMIT: '${{ github.event.after }}'
          EVENT_BEFORE_COMMIT: '${{ github.event.before }}'
          EVENT_COMPARE_URL: '${{ github.event.compare }}'
      - name: 'Slack notification'
        id: slack
        uses: slackapi/slack-github-action@v1.27.0
        with:
          channel-id: 'jsbuffer'
          payload-file-path: '.github/workflows/test-finished-slack-message.json'
        env:
          SLACK_BOT_TOKEN: ${{ secrets.SLACK_BOT_TOKEN }}
